!CALCULA LAMBDA ATRAVES DA FUNCAO SELECIONADA (PEDRO GODOI 2020)
 SUBROUTINE FUNCAO_LAMBDA(NB,DADOS_LAMBDA,OCUP,POP,POP_PAS,LAMBDA)
 
 IMPLICIT NONE 

 TYPE::F_LAMBDA
	INTEGER        ::BL4  ; &
	REAL(KIND=10)  ::L_ZERO ; &
	CHARACTER(13)  ::MOD_LAMBDA
				  !CONSTANTE:       LAMBDA = L_ZERO 
				  !TIAGO:           LAMBDA = L_ZERO + L_ZERO*(DELTA_OCUP + DELTA_POP)

 END TYPE

 INTEGER,INTENT(IN)				                ::NB
 TYPE(F_LAMBDA),DIMENSION(NB),INTENT(IN)	    ::DADOS_LAMBDA
 REAL(KIND=10),INTENT(IN)                       ::OCUP,POP,POP_PAS
 REAL(KIND=10),INTENT(OUT)			            ::LAMBDA

 
 
 LAMBDA=0.0
 
 SELECT CASE (DADOS_LAMBDA(1)%MOD_LAMBDA)
 
    CASE('CONSTANTE')
    
    LAMBDA = DADOS_LAMBDA(1)%L_ZERO
    
    CASE('TIAGO')
    
    LAMBDA = DADOS_LAMBDA(1)%L_ZERO + DADOS_LAMBDA(1)%L_ZERO * ((100.0/OCUP) + (POP/POP_PAS))

 END SELECT
 
 
 END SUBROUTINE FUNCAO_LAMBDA
