
 SUBROUTINE MALHA(COMPDOM,NI,COMP_DOMI,DELTA_X,X,XS)
 
 IMPLICIT NONE 

  TYPE::DOMINIO
	REAL(KIND=10)	::DOM1 ; REAL(KIND=10) ::DOM2 ; &
	CHARACTER(3) 	::DOM3
 END TYPE

 
 TYPE(DOMINIO),INTENT(IN)			           ::COMPDOM
 INTEGER,INTENT(IN)				               ::NI
 REAL(KIND=10),INTENT(IN)			           ::COMP_DOMI
 REAL(KIND=10),INTENT(OUT)			           ::DELTA_X
 REAL(KIND=10),DIMENSION(NI+2),INTENT(INOUT)	   ::X
 REAL(KIND=10),DIMENSION(NI+1),INTENT(INOUT)   ::XS


 !DECLARAÇÃO DAS VARIÁVEIS LOCAIS
 INTEGER	::I

 
 DELTA_X = ( COMP_DOMI - COMPDOM%DOM1 ) / ( NI - 1 )
    
    
 !!! CRIA A MALHA X !!!
 X(1) = COMPDOM%DOM1 - DELTA_X
 X(2) = COMPDOM%DOM1
      
 DO I=3,NI
      X(I)= X(I-1) + DELTA_X
 END DO 
      
 X(NI+1) = COMP_DOMI
 X(NI+2) = COMP_DOMI + DELTA_X
 
 !!! CRIA A MALHA XS !!!
 XS(1) = X(1) + (DELTA_X / 2)
 
 DO I=2,NI+1
    XS(I)= XS(I-1) + DELTA_X
 END DO
 
  
 END SUBROUTINE MALHA
