!CALCULA A OCUPACAO (PEDRO GODOI 2020)
 SUBROUTINE OCUPACAO2D(NI,MJ,TOL_OCUP,S2D,OCUP)
 
 IMPLICIT NONE 


 INTEGER,INTENT(IN)				                    ::NI,MJ
 REAL(KIND=10),INTENT(IN)			                ::TOL_OCUP
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(IN)	    ::S2D
 REAL(KIND=10),INTENT(OUT)                          ::OCUP


 !DECLARAÇÃO DAS VARIÁVEIS LOCAIS
 INTEGER	        ::I,J
 
 !INICIA VALORES
 OCUP=0.0
 
 DO J=2,MJ                              !NAO CONSIDERA AS CELULAS FANTASMA
    DO I=2,NI
        IF (S2D(J,I) > TOL_OCUP) THEN
        OCUP = OCUP+1.0
        END IF
    END DO
 END DO
 
 !PORCENTAGEM
 OCUP = (OCUP*100)/((NI-1)*(MJ-1))
  
 END SUBROUTINE OCUPACAO2D
