
 SUBROUTINE COND_CONTORNO2D(NI,MJ,NB,CONDCONTORNO,DELTA_X,DELTA_Y,S2D,S2D_PAS)

 
 IMPLICIT NONE 

 !DECLARAÇÃO DAS VARIÁVEIS DA SUBROTINA
 TYPE::CONDICOES_CONT
	INTEGER 	::PRI 
	REAL(KIND=10)	::CC1W ; REAL(KIND=10) ::CC2W
	REAL(KIND=10)	::CC1E ; REAL(KIND=10) ::CC2E
    REAL(KIND=10)	::CC1S ; REAL(KIND=10) ::CC2S
	REAL(KIND=10)	::CC1N ; REAL(KIND=10) ::CC2N
 END TYPE

 INTEGER,INTENT(IN)					                    ::NI,MJ,NB
 TYPE(CONDICOES_CONT),DIMENSION(NB),INTENT(IN)		    ::CONDCONTORNO
 REAL(KIND=10),INTENT(IN)				                ::DELTA_X, DELTA_Y
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(INOUT)		::S2D,S2D_PAS
 


 !DECLARAÇÃO DAS VARIÁVEIS LOCAIS
 INTEGER	    ::BLOCO,I,J
 REAL(KIND=10)	::F
 !----------

 ! DEFINIÇÃO DAS CONDICOES DE CONTORNO PARA A DENSIDADE POPULACIONAL
 
 DO BLOCO = 1,NB
 
    DO J=2,MJ !!! LESTE OESTE !!!
 
      ! CONTORNO "" W ""
      
      F = 0.0
      
      S2D(J,1) = ( DELTA_X / (DELTA_X*CONDCONTORNO(BLOCO)%CC2W + 3.0*CONDCONTORNO(BLOCO)%CC1W) ) *&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1W/DELTA_X) * ( 3.5*S2D(J,2) - 0.5*S2D(J,3) ) )

	      
      S2D_PAS(J,1) = ( DELTA_X / (DELTA_X*CONDCONTORNO(BLOCO)%CC2W + 3.0*CONDCONTORNO(BLOCO)%CC1W) ) *&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1W/DELTA_X) * ( 3.5*S2D_PAS(J,2) - 0.5*S2D_PAS(J,3) ) )
      
      ! CONTORNO "" E ""

      F = 0.0
      
      S2D(J,NI+1) = ( DELTA_X / (DELTA_X*CONDCONTORNO(BLOCO)%CC2E + 3.0*CONDCONTORNO(BLOCO)%CC1E) )*&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1E/DELTA_X) * ( 3.5*S2D(J,NI) - 0.5*S2D(J,NI-1) ) )

	      
      S2D_PAS(J,NI+1) = ( DELTA_X / (DELTA_X*CONDCONTORNO(BLOCO)%CC2E + 3.0*CONDCONTORNO(BLOCO)%CC1E) )*&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1E/DELTA_X) * ( 3.5*S2D_PAS(J,NI) - 0.5*S2D_PAS(J,NI-1) ) )
	      
    END DO

    
    
    DO I=2,NI !!! NORTE SUL !!!
 
      ! CONTORNO "" S ""
      
      F = 0.0
      
      S2D(1,I) = ( DELTA_Y / (DELTA_Y*CONDCONTORNO(BLOCO)%CC2S + 3.0*CONDCONTORNO(BLOCO)%CC1S) ) *&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1S/DELTA_Y) * ( 3.5*S2D(2,I) - 0.5*S2D(3,I) ) )

	      
      S2D_PAS(1,I) = ( DELTA_Y / (DELTA_Y*CONDCONTORNO(BLOCO)%CC2S + 3.0*CONDCONTORNO(BLOCO)%CC1S) ) *&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1S/DELTA_Y) * ( 3.5*S2D_PAS(2,I) - 0.5*S2D_PAS(3,I) ) )
      
      ! CONTORNO "" N ""

      F = 0.0
      
      S2D(MJ+1,I) = ( DELTA_Y / (DELTA_Y*CONDCONTORNO(BLOCO)%CC2N + 3.0*CONDCONTORNO(BLOCO)%CC1N) )*&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1N/DELTA_Y) * ( 3.5*S2D(MJ,I) - 0.5*S2D(MJ-1,I) ) )

	      
      S2D_PAS(MJ+1,I) = ( DELTA_Y / (DELTA_Y*CONDCONTORNO(BLOCO)%CC2N + 3.0*CONDCONTORNO(BLOCO)%CC1N) )*&
      
	      ( F + (CONDCONTORNO(BLOCO)%CC1N/DELTA_Y) * ( 3.5*S2D_PAS(MJ,I) - 0.5*S2D_PAS(MJ-1,I) ) )
	      
    END DO
    
    
    !!! QUATRO CANTOS !!!
    S2D(1,1)=(S2D(1,2)+S2D(2,1))/2
    S2D(1,NI+1)=(S2D(1,NI)+S2D(2,NI+1))/2
    S2D(MJ+1,1)=(S2D(MJ,1)+S2D(MJ+1,2))/2
    S2D(MJ+1,NI+1)=(S2D(MJ+1,NI)+S2D(MJ,NI+1))/2
    
    S2D_PAS(1,1)=(S2D_PAS(1,2)+S2D_PAS(2,1))/2
    S2D_PAS(1,NI+1)=(S2D_PAS(1,NI)+S2D_PAS(2,NI+1))/2
    S2D_PAS(MJ+1,1)=(S2D_PAS(MJ,1)+S2D_PAS(MJ+1,2))/2
    S2D_PAS(MJ+1,NI+1)=(S2D_PAS(MJ+1,NI)+S2D_PAS(MJ,NI+1))/2
    
    
    
 END DO




 END SUBROUTINE COND_CONTORNO2D
