! RESOLVE A EQUAÇAO TELEGRAFICA-REATIVA-DIFUSIVA-2D PELO ESQUEMA TOTALMENTE IMPLICITO 
 SUBROUTINE EQUACAO_S2D_ELIANDRO(NB,NI,MJ,DELTA_X,DELTA_Y,XS,YS,DELTA_T,FONTE,K1VAR,K2VAR,K3VAR,IT_SOL,W_SOL,TOL_SOL,&
            S2D_PAS,S2D_PAS_PAS,S2D,DADOS_LAMBDA,OCUP,TOL_OCUP,POP,POP_PAS,DADOS_GAMMA_X,DADOS_GAMMA_Y,&
            S2D_LAMBDA,S2D_VEL_X,S2D_VEL_Y,S2D_VS,CONVERGE)
 
 IMPLICIT NONE 
 
 TYPE::FONTE_INIC
	INTEGER        ::BL3  ; &
	REAL(KIND=10)  ::K1IN,K1STEP,K1END,K2IN,K2STEP,K2END,K3IN,K3STEP,K3END ; &
	CHARACTER(14)  ::MOD_F
 END TYPE
 
 TYPE::F_LAMBDA
	INTEGER        ::BL4  ; &
	REAL(KIND=10)  ::L_ZERO ; &
	CHARACTER(13)  ::MOD_LAMBDA
				  !CONSTANTE:       LAMBDA = L_ZERO 
				  !TIAGO:           LAMBDA = L_ZERO + L_ZERO*(DELTA_OCUP + DELTA_POP)
 END TYPE

 TYPE::F_GAMMA
	INTEGER        ::BL5  ; &
	REAL(KIND=10)  ::GAMMA_ZERO ; &
	CHARACTER(13)  ::MOD_GAMMA

 END TYPE
 
 INTEGER,INTENT(IN)				                    ::NB,NI,MJ,IT_SOL
 REAL(KIND=10),INTENT(IN)			                ::DELTA_X,DELTA_Y,DELTA_T   !,VEL_X,VEL_Y
 TYPE(FONTE_INIC),DIMENSION(NB),INTENT(IN)	        ::FONTE
 TYPE(F_LAMBDA),DIMENSION(NB),INTENT(IN)	        ::DADOS_LAMBDA
 TYPE(F_GAMMA),DIMENSION(NB),INTENT(IN)             ::DADOS_GAMMA_X,DADOS_GAMMA_Y
 REAL(KIND=10),INTENT(IN)		                 	::W_SOL,TOL_SOL,K1VAR,K2VAR,K3VAR,POP_PAS,TOL_OCUP
 REAL(KIND=10),DIMENSION(NI+1),INTENT(IN)           ::XS
 REAL(KIND=10),DIMENSION(MJ+1),INTENT(IN)           ::YS
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(IN)	    ::S2D_PAS,S2D_PAS_PAS
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(INOUT)	::S2D
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(OUT)     ::S2D_LAMBDA,S2D_VEL_X,S2D_VEL_Y,S2D_VS
 REAL(KIND=10),INTENT(OUT)                          ::OCUP,POP  !,LAMBDA
 LOGICAL,INTENT(OUT)                                ::CONVERGE
 


 !DECLARAÇÃO DAS VARIÁVEIS LOCAIS
 INTEGER	                             ::J,I,IT
 REAL(KIND=10)                           ::CN,CS,CW,CE,CP,LAMBDA,VEL_X,VEL_Y              
 REAL(KIND=10)                           ::CP_TIL,B_TIL,B_BAR,F_S,D_F_S,TAU
 REAL(KIND=10)                           ::X,Y
 REAL(KIND=10)                           ::SATUAL,S_DIF,S_INF,VS,ERRO
 REAL(KIND=10),DIMENSION(MJ+1,NI+1)	     ::S2DNOVO,S2DNOVO_PAS
 
 
 !!! RESETA TESTE DE CONVERGENCIA !!!
 CONVERGE=.FALSE.
 
 
 !!! DEBUG !!!
 !VEL_X=1.0
 !VEL_Y=1.0
 
 
 !!! INICIALIZA S2DNOVO !!!
 S2DNOVO=S2D

 
 !!! RESOLVE O SISTEMA !!!
 
 !!!PRIMEIRO PASSO
 DO J=2,MJ
 
 DO I=2,NI
 
 !CARREGA VALOR ATUAL DE S e S_INF
 SATUAL=S2D(J,I)
 S_INF=S2D_PAS(J,I)
 
 !VERIFICA S_INF (SE FOR IGUAL A ZERO TOMAR A MEDIA DA VIZINHANCA)
 IF (S_INF == 0.0) THEN
 S_INF = (S2D_PAS(J+1,I) + S2D_PAS(J-1,I) + S2D_PAS(J,I+1) + S2D_PAS(J,I-1))/4.0
 END IF
 
 !CALCULA TERMO FONTE
 CALL TERMO_FONTE(NB,FONTE,SATUAL,K1VAR,K2VAR,K3VAR,F_S,D_F_S)
 
 !(A) CALCULA O VALOR DE S
 S2DNOVO(J,I)= DELTA_T*F_S + S2D_PAS(J,I)
 
 !(B) CALCULA Vs
 IF (DADOS_LAMBDA(1)%MOD_LAMBDA == 'ELIANDRO') THEN
 VS = ABS((S2DNOVO(J,I)-S2D_PAS(J,I))) / DELTA_T
 ELSE
 VS = (S2DNOVO(J,I)-S2D_PAS(J,I)) / DELTA_T
 END IF
 
 S2D_VS(J,I)=VS
 
 !(C) CALCULA LAMBDA
 IF (S_INF /= 0.0) THEN
 LAMBDA = VS / S_INF
 ELSE
 LAMBDA=500.0                       !VALOR ARBITRARIAMENTE ALTO (NÃO UTILIZADO EM CONTA ALGUMA)
 END IF
 
 IF (LAMBDA == 0.0) THEN
 LAMBDA = 0.000000000001            !CHUTE INICIAL PARA LAMBDA
 END IF
 
 S2D_LAMBDA(J,I)=LAMBDA
 
 
 END DO !J
 
 END DO !I
 
 
 
 !!!PREPARA PROCESSO ITERATIVO
 S2DNOVO_PAS=S2D                !VALOR ANTES DA ITERACAO
 S2D=S2DNOVO                    !VALOR ITERADO
 
 
 
 !!!PROCESSO ITERATIVO
 DO IT=1,IT_SOL
 
 !CALCULA COEFICIENTES NAO LINEARES GERAIS
 
 DO J=2,MJ
 
 DO I=2,NI
 
 !CARREGA VALORES DE S E S_INF
 SATUAL=S2D(J,I)
 S_INF=S2DNOVO_PAS(J,I)
 
 !VERIFICA S_INF (SE FOR IGUAL A ZERO TOMAR A MEDIA DA VIZINHANCA)
 IF (S_INF == 0.0) THEN
 S_INF = (S2DNOVO_PAS(J+1,I) + S2DNOVO_PAS(J-1,I) + S2DNOVO_PAS(J,I+1) + S2DNOVO_PAS(J,I-1))/4.0
 END IF
 
 !CALCULA TERMO FONTE
 CALL TERMO_FONTE(NB,FONTE,SATUAL,K1VAR,K2VAR,K3VAR,F_S,D_F_S)
 
 
 !!!(A) CALCULA VALOR DE S
 IF (S_INF == 0.0) THEN                           !SE S_INF = 0 (-> S=0)
        S2DNOVO(J,I)=0.0
 
 ELSE                                             !SE S_INF =\= 0 (-> S=TELEGRAFICA)
 
        CALL FUNCAO_GAMMA(NB,DADOS_GAMMA_X,X,Y,VEL_X) !VEL_X
        S2D_VEL_X(J,I)=VEL_X
  
        CALL FUNCAO_GAMMA(NB,DADOS_GAMMA_Y,X,Y,VEL_Y) !VEL_Y
        S2D_VEL_Y(J,I)=VEL_Y
        
        LAMBDA = S2D_LAMBDA(J,I)
        
        TAU=1.0/(2.0*LAMBDA)
 
        CW = ((VEL_X**2)/(2*LAMBDA))*(1/(DELTA_X**2))
        CE = CW
 
        CN = ((VEL_Y**2)/(2*LAMBDA))*(1/(DELTA_Y**2))
        CS = CN
 
        CP = (1/DELTA_T) + 2*CN + 2*CE
 
        CP_TIL = (1/(DELTA_T**2)) - ((1/DELTA_T)*D_F_S)
 
        B_TIL = ((2/(DELTA_T**2)) - ((1/DELTA_T)*D_F_S))*S2D_PAS(J,I) - (1/(DELTA_T**2))*S2D_PAS_PAS(J,I)
 
        B_BAR = (1/DELTA_T)*S2D_PAS(J,I) + F_S
        
        S2DNOVO(J,I)=(1/(CP + TAU*CP_TIL)) * (CS*S2DNOVO(J-1,I) + CW*S2DNOVO(J,I-1) + CN*S2D(J+1,I) +&
        CE*S2D(J,I+1) + B_BAR + TAU*B_TIL)
 END IF
 
 
 !(B) CALCULA Vs
 IF (DADOS_LAMBDA(1)%MOD_LAMBDA == 'ELIANDRO') THEN
 VS = ABS((S2DNOVO(J,I)-S2D_PAS(J,I))) / DELTA_T
 ELSE
 VS = (S2DNOVO(J,I)-S2D_PAS(J,I)) / DELTA_T
 END IF
 
 S2D_VS(J,I)=VS
 
 !(C) CALCULA LAMBDA
 IF (S_INF /= 0.0) THEN
 LAMBDA = VS / S_INF
 ELSE
 LAMBDA=500.0                           !VALOR ARBITRARIAMENTE ALTO (NÃO UTILIZADO EM CONTA ALGUMA)
 END IF
 
 IF (LAMBDA == 0.0) THEN
 LAMBDA = 0.000000000001                !CHUTE INICIAL PARA LAMBDA
 END IF
 
 S2D_LAMBDA(J,I)=LAMBDA
 
 
 END DO !I
 
 END DO !J
 
 !ERRO
 ERRO=NORM2(S2DNOVO-S2D)/NORM2(S2DNOVO)
 
 IF (ERRO <= TOL_SOL) THEN
 
    S2DNOVO_PAS = S2D 
    S2D = S2DNOVO
    CONVERGE=.TRUE.
    GOTO 101
    
 END IF 
 
 !PREPARA PROXIMA ITERACAO
 S2DNOVO_PAS=S2D                !VALOR ANTES DA ITERACAO
 S2D=S2DNOVO                    !VALOR ITERADO
 
 END DO !IT
 
 101 CONTINUE
 
 
 !!!ITERACAO EXTRA
 
 
 !CALCULA COEFICIENTES NAO LINEARES GERAIS
 
 DO J=2,MJ
 
 DO I=2,NI
 
 !CARREGA VALORES DE S E S_INF
 SATUAL=S2D(J,I)
 S_INF=S2DNOVO_PAS(J,I)
 
 !VERIFICA S_INF (SE FOR IGUAL A ZERO TOMAR A MEDIA DA VIZINHANCA)
 IF (S_INF == 0.0) THEN
 S_INF = (S2DNOVO_PAS(J+1,I) + S2DNOVO_PAS(J-1,I) + S2DNOVO_PAS(J,I+1) + S2DNOVO_PAS(J,I-1))/4.0
 END IF
 
 !CALCULA TERMO FONTE
 CALL TERMO_FONTE(NB,FONTE,SATUAL,K1VAR,K2VAR,K3VAR,F_S,D_F_S)
 
 
 !!!(A) CALCULA VALOR DE S
 IF (S_INF == 0.0) THEN                           !SE S_INF = 0 (-> S=0)
        S2DNOVO(J,I)=0.0
 
 ELSE                                             !SE S_INF =\= 0 (-> S=TELEGRAFICA)
 
        CALL FUNCAO_GAMMA(NB,DADOS_GAMMA_X,X,Y,VEL_X) !VEL_X
        S2D_VEL_X(J,I)=VEL_X
  
        CALL FUNCAO_GAMMA(NB,DADOS_GAMMA_Y,X,Y,VEL_Y) !VEL_Y
        S2D_VEL_Y(J,I)=VEL_Y
        
        LAMBDA = S2D_LAMBDA(J,I)
        
        TAU=1.0/(2.0*LAMBDA)
 
        CW = ((VEL_X**2)/(2*LAMBDA))*(1/(DELTA_X**2))
        CE = CW
 
        CN = ((VEL_Y**2)/(2*LAMBDA))*(1/(DELTA_Y**2))
        CS = CN
 
        CP = (1/DELTA_T) + 2*CN + 2*CE
 
        CP_TIL = (1/(DELTA_T**2)) - ((1/DELTA_T)*D_F_S)
 
        B_TIL = ((2/(DELTA_T**2)) - ((1/DELTA_T)*D_F_S))*S2D_PAS(J,I) - (1/(DELTA_T**2))*S2D_PAS_PAS(J,I)
 
        B_BAR = (1/DELTA_T)*S2D_PAS(J,I) + F_S
        
        S2DNOVO(J,I)=(1/(CP + TAU*CP_TIL)) * (CS*S2DNOVO(J-1,I) + CW*S2DNOVO(J,I-1) + CN*S2D(J+1,I) +&
        CE*S2D(J,I+1) + B_BAR + TAU*B_TIL)
 END IF
 
 
 END DO !I
 
 END DO !J
 
 !ERRO
 ERRO=NORM2(S2DNOVO-S2D)/NORM2(S2DNOVO)
 
 
 
 !PRINT*, 'ITERACOES:',IT
 !PRINT*, 'ERRO:', ERRO
 
 !CALCULA COEFICIENTES NAO LINEARES GERAIS
 CALL OCUPACAO2D(NI,MJ,TOL_OCUP,S2D,OCUP) !OCUPACAO
 
 CALL INTEGRAL2D(NI,MJ,DELTA_X,DELTA_Y,S2D,POP) !POPULACAO
 
  
 END SUBROUTINE EQUACAO_S2D_ELIANDRO
