!CALCULA GAMMA ATRAVES DA FUNCAO SELECIONADA (PEDRO GODOI 2020)
 SUBROUTINE FUNCAO_GAMMA(NB,DADOS_GAMMA,X,Y,VEL)
 
 IMPLICIT NONE 

 TYPE::F_GAMMA
	INTEGER        ::BL5  ; &
	REAL(KIND=10)  ::GAMMA_ZERO ; &
	CHARACTER(13)  ::MOD_GAMMA

 END TYPE

 INTEGER,INTENT(IN)                        ::NB
 TYPE(F_GAMMA),DIMENSION(NB),INTENT(IN)    ::DADOS_GAMMA
 REAL(KIND=10),INTENT(IN)                  ::X,Y
 REAL(KIND=10),INTENT(OUT)                 ::VEL

 
 
 VEL=0.0
 
 SELECT CASE (DADOS_GAMMA(1)%MOD_GAMMA)
 
    CASE('CONSTANTE')
    
    VEL = DADOS_GAMMA(1)%GAMMA_ZERO
    
    CASE('TESTE')
    
    IF ((X>=500) .AND. (X<=700)) THEN
        VEL = DADOS_GAMMA(1)%GAMMA_ZERO*0.2
    ELSE
        VEL = DADOS_GAMMA(1)%GAMMA_ZERO
    END IF
    


 END SELECT
 
 
 END SUBROUTINE FUNCAO_GAMMA
