!CALCULA QUANTIDADES DE INTERESSE
 SUBROUTINE QUANTIDADES(NB,CICLO,NI,MJ,DELTA_X,DELTA_Y,DELTA_T,S2D_VEL_X,S2D_VEL_Y,FONTE,T,S2D,S2D_PAS,S2D_PAS_PAS,&
                        K1VAR,K2VAR,K3VAR,POP,OCUP,S2D_LAMBDA,ERRO_EST)
 
 IMPLICIT NONE
 
 TYPE::FONTE_INIC
	INTEGER        ::BL3  ; &
	REAL(KIND=10)  ::K1IN,K1STEP,K1END,K2IN,K2STEP,K2END,K3IN,K3STEP,K3END ; &
	CHARACTER(14)  ::MOD_F
 END TYPE
 
 
 INTEGER,INTENT(IN)				                    ::NB,CICLO,NI,MJ
 REAL(KIND=10),INTENT(IN)			                ::DELTA_X,DELTA_Y,DELTA_T,T,K1VAR,K2VAR,K3VAR
 REAL(KIND=10),INTENT(IN)                           ::OCUP,POP,ERRO_EST
 REAL(KIND=10),DIMENSION(MJ+1,NI+1),INTENT(IN)	    ::S2D,S2D_PAS,S2D_PAS_PAS,S2D_LAMBDA,S2D_VEL_X,S2D_VEL_Y
 TYPE(FONTE_INIC),DIMENSION(NB),INTENT(IN)	        ::FONTE
 
 !VARIAVEIS DA SUBROTINA
 INTEGER                ::I,J
 REAL(KIND=10)          ::VEL_X,VEL_Y,LAMBDA
 REAL(KIND=10)          ::SATUAL,F_S,D_F_S,TAU,D_X,D_Y
 REAL(KIND=10)          ::PARCELA_REATIVA,PARCELA_TEMPORAL,PARCELA_DIFUSIVAX,PARCELA_DIFUSIVAY
 REAL(KIND=10)          ::TOTAL_PARCELAS,PROVA_REAL
 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!! INICIALIZA VARIAVEIS LOCAIS !!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 SATUAL=0.0; F_S=0.0; D_F_S=0.0
 PARCELA_REATIVA=0.0; PARCELA_TEMPORAL=0.0; PARCELA_DIFUSIVAX=0.0; PARCELA_DIFUSIVAY=0.0
 TOTAL_PARCELAS=0.0; PROVA_REAL=0.0
 
 TAU=0.0; D_X=0.0; D_Y=0.0
 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!! ABRE O ARQUIVO PARA GRAVAR OS RESULTADOS !!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 !IF (CICLO==0) THEN
 !OPEN(1,FILE='QUANT_POPULACIONAL.dat',STATUS='NEW')
 !ELSE
 !OPEN(1,FILE='QUANT_POPULACIONAL.dat',STATUS='OLD',POSITION='APPEND')
 !END IF
 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!! CALCULA QUANTIDADES DE INTERESSE !!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 !POPULACAO
 
 !CALL INTEGRAL2D(NI,MJ,DELTA_X,DELTA_Y,S2D,POP)
 
 !PARCELAS DA EDP
 
 DO J=2,MJ
    DO I=2,NI
    
        !TERMOS PONTUAIS
        
        SATUAL=S2D(J,I)
        
        VEL_X=S2D_VEL_X(J,I)
        VEL_Y=S2D_VEL_Y(J,I)
        LAMBDA=S2D_LAMBDA(J,I)
        
        TAU=1/(2*LAMBDA)
        D_X=(VEL_X**2)/(2*LAMBDA)
        D_Y=(VEL_Y**2)/(2*LAMBDA)
        
        !CALCULA TERMO FONTE
        
        CALL TERMO_FONTE(NB,FONTE,SATUAL,K1VAR,K2VAR,K3VAR,F_S,D_F_S)
        
        !PARCELA REATIVA
        
        PARCELA_REATIVA = PARCELA_REATIVA + F_S
        
        !PARCELA TEMPORAL
        
        PARCELA_TEMPORAL = PARCELA_TEMPORAL + (TAU/(DELTA_T**2))*(S2D(J,I)-2*S2D_PAS(J,I)+S2D_PAS_PAS(J,I)) +&
                                              (1-TAU*D_F_S)*(1/DELTA_T)*(S2D(J,I)-S2D_PAS(J,I))
                                              
        !PARCELA DIFUSIVA X
        
        PARCELA_DIFUSIVAX = PARCELA_DIFUSIVAX + (D_X/(DELTA_X**2))*(S2D(J,I-1)-2*S2D(J,I)+S2D(J,I+1))
        
        !PARCELA DIFUSIVA Y
        
        PARCELA_DIFUSIVAY = PARCELA_DIFUSIVAY + (D_Y/(DELTA_Y**2))*(S2D(J-1,I)-2*S2D(J,I)+S2D(J+1,I))
        
    END DO
 END DO
 
 !PROVA REAL
 PROVA_REAL = PARCELA_TEMPORAL - PARCELA_REATIVA - PARCELA_DIFUSIVAX - PARCELA_DIFUSIVAY
 
 !TOTAL PARCELAS
 TOTAL_PARCELAS = PARCELA_REATIVA + PARCELA_TEMPORAL + PARCELA_DIFUSIVAX + PARCELA_DIFUSIVAY
 
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!
 !!! CALCULO PELA MEDIA !!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!
 
 !PARCELA_REATIVA   = (1/((NI+1)*(MJ+1))) * PARCELA_REATIVA
 !PARCELA_TEMPORAL  = (1/((NI+1)*(MJ+1))) * PARCELA_TEMPORAL
 !PARCELA_DIFUSIVAX = (1/((NI+1)*(MJ+1))) * PARCELA_DIFUSIVAX
 !PARCELA_DIFUSIVAY = (1/((NI+1)*(MJ+1))) * PARCELA_DIFUSIVAY
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!
 !!! ESCREVE NO ARQUIVO !!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!
 
 IF (CICLO==0) THEN
 
 WRITE(1,10)

 10 FORMAT(05X,'# Tempo',22X,'POP_NUMERICA',22X,'PARC_REATIVA',22X,'PAR_TEMPORAL',22X,'P_DIFUSIVA_X',22X,'P_DIFUSIVA_Y',&
          22X,'_____RESIDUO',22X,'OCUPACAO_NUM',22X,'ERRO_ESTACIO')
 
 ELSE
 
 WRITE(1,11) T,POP,PARCELA_REATIVA,PARCELA_TEMPORAL,PARCELA_DIFUSIVAX,PARCELA_DIFUSIVAY,ABS(PROVA_REAL),OCUP,ERRO_EST
 
 11 FORMAT(F12.4,22X,E12.4,22X,E12.4,22X,E12.4,22X,E12.4,22X,E12.4,22X,E12.4,22X,F12.8,22X,F12.8)
 !         T         POP       REAC      TEMP      DIFX      DIFY      RES       OCUP      E_EST
 
 END IF
 
 !CLOSE(1)
 
 END SUBROUTINE QUANTIDADES
