!CALCULA SPLINE CUBICA NATURAL PARAMETRICA CONFORME LIVRO DO BURDEN (PEDRO GODOI 2020)
SUBROUTINE SPLINEPAR_PRINCIPAL(LADO,ITMAX,DIV,GS_TOL,SPL_LIN,SPL)

IMPLICIT NONE

!IN
INTEGER, INTENT(IN)                 ::ITMAX, SPL_LIN,DIV !Numero de pontos a interpolar entre cada valor
REAL, INTENT(IN)                    ::GS_TOL

!OUT
REAL, DIMENSION(2,SPL_LIN), INTENT(OUT)   ::SPL

!LOCAL
INTEGER                             ::I,LIN,CONTROLE,MANIPULA,LADO
REAL, DIMENSION(:,:), ALLOCATABLE   ::DADOS_ENTX,DADOS_ENTY
REAL, DIMENSION(2,SPL_LIN)          ::SPLX,SPLY



!APAGA ARQUIVOS ANTERIORES
IF (LADO==1) THEN
MANIPULA = SYSTEM('if test -e splineparE.dat; then rm splineparE.dat; fi;')
ELSE
MANIPULA = SYSTEM('if test -e splineparD.dat; then rm splineparD.dat; fi;')
END IF

IF (LADO==1) THEN
!VERIFICA NUMERO DE PONTOS NO ARQUIVO DE ENTRADA
OPEN(1,FILE='SPLINE/entrada_spline_E.dat',STATUS='OLD')
ELSE
OPEN(1,FILE='SPLINE/entrada_spline_D.dat',STATUS='OLD')
END IF
LIN=0

DO
READ(1,*,IOSTAT = CONTROLE)
    IF(CONTROLE < 0) EXIT
    LIN = LIN + 1
END DO
CLOSE(1)

!LE O ARQUIVO DE ENTRADA
ALLOCATE(DADOS_ENTX(2,LIN),DADOS_ENTY(2,LIN))

IF (LADO==1) THEN
OPEN(2,FILE='SPLINE/entrada_spline_E.dat',STATUS='OLD')
ELSE
OPEN(2,FILE='SPLINE/entrada_spline_D.dat',STATUS='OLD')
END IF

DO I=1,LIN
    DADOS_ENTX(1,I)=I
    DADOS_ENTY(1,I)=I
    READ(2,*) DADOS_ENTX(2,I),DADOS_ENTY(2,I)
END DO

!AJUSTA VALORES PARA A MALHA
DADOS_ENTX(2,:)=DADOS_ENTX(2,:)-0.5
DADOS_ENTY(2,:)=DADOS_ENTY(2,:)-0.5


!DEBUG 1
!PRINT*, DADOS_ENT(1,:)
!PRINT*, DADOS_ENT(2,:)

!CALCULA SPLINE

!DEBUG 2
!PRINT*, SIZE(DADOS_ENTX,DIM=2)
!PRINT*, SIZE(SPLX,DIM=2)


CALL SPLINE_CALC(DADOS_ENTX,LIN,DIV,ITMAX,GS_TOL,SPL_LIN,SPLX)
CALL SPLINE_CALC(DADOS_ENTY,LIN,DIV,ITMAX,GS_TOL,SPL_LIN,SPLY)

!DEBUG 3 
!PRINT*, SPL(1,:)
!PRINT*, SPL(2,:)


!ESCREVE RESULTADOS PARA ARQUIVO
IF (LADO==1) THEN
OPEN(3,FILE='splineparE.dat',STATUS='NEW')
ELSE
OPEN(3,FILE='splineparD.dat',STATUS='NEW')
END IF

DO I=1,SPL_LIN
    WRITE(3,100) SPLX(2,I),SPLY(2,I)
END DO

100 FORMAT(F12.4,4X,F12.4)

CLOSE(3)

!ESCREVE SAIDA
SPL(1,:)=SPLX(2,:)
SPL(2,:)=SPLY(2,:)



END SUBROUTINE SPLINEPAR_PRINCIPAL
